# Generated by Django 3.0.8 on 2020-07-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_id', models.IntegerField(max_length=11)),
                ('comp_info', models.CharField(max_length=1000)),
                ('comp_desc', models.CharField(max_length=1000)),
                ('comp_price', models.CharField(max_length=11)),
                ('comp_type', models.IntegerField(max_length=3)),
            ],
        ),
    ]
