# Generated by Django 3.0.8 on 2020-07-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='comp_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='component',
            name='comp_type',
            field=models.IntegerField(),
        ),
    ]
